# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.9.1/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.9.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/kvfs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/kvfs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.9.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.9.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/kvfs/CMakeFiles /root/kvfs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/kvfs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fs_main

# Build rule for target.
fs_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fs_main
.PHONY : fs_main

# fast build rule for target.
fs_main/fast:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/build
.PHONY : fs_main/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

fs/adaptor.o: fs/adaptor.cpp.o

.PHONY : fs/adaptor.o

# target to build an object file
fs/adaptor.cpp.o:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/adaptor.cpp.o
.PHONY : fs/adaptor.cpp.o

fs/adaptor.i: fs/adaptor.cpp.i

.PHONY : fs/adaptor.i

# target to preprocess a source file
fs/adaptor.cpp.i:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/adaptor.cpp.i
.PHONY : fs/adaptor.cpp.i

fs/adaptor.s: fs/adaptor.cpp.s

.PHONY : fs/adaptor.s

# target to generate assembly for a file
fs/adaptor.cpp.s:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/adaptor.cpp.s
.PHONY : fs/adaptor.cpp.s

fs/config.o: fs/config.cpp.o

.PHONY : fs/config.o

# target to build an object file
fs/config.cpp.o:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/config.cpp.o
.PHONY : fs/config.cpp.o

fs/config.i: fs/config.cpp.i

.PHONY : fs/config.i

# target to preprocess a source file
fs/config.cpp.i:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/config.cpp.i
.PHONY : fs/config.cpp.i

fs/config.s: fs/config.cpp.s

.PHONY : fs/config.s

# target to generate assembly for a file
fs/config.cpp.s:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/config.cpp.s
.PHONY : fs/config.cpp.s

fs/inode.o: fs/inode.cpp.o

.PHONY : fs/inode.o

# target to build an object file
fs/inode.cpp.o:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/inode.cpp.o
.PHONY : fs/inode.cpp.o

fs/inode.i: fs/inode.cpp.i

.PHONY : fs/inode.i

# target to preprocess a source file
fs/inode.cpp.i:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/inode.cpp.i
.PHONY : fs/inode.cpp.i

fs/inode.s: fs/inode.cpp.s

.PHONY : fs/inode.s

# target to generate assembly for a file
fs/inode.cpp.s:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/inode.cpp.s
.PHONY : fs/inode.cpp.s

fs/kvfs.o: fs/kvfs.cpp.o

.PHONY : fs/kvfs.o

# target to build an object file
fs/kvfs.cpp.o:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/kvfs.cpp.o
.PHONY : fs/kvfs.cpp.o

fs/kvfs.i: fs/kvfs.cpp.i

.PHONY : fs/kvfs.i

# target to preprocess a source file
fs/kvfs.cpp.i:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/kvfs.cpp.i
.PHONY : fs/kvfs.cpp.i

fs/kvfs.s: fs/kvfs.cpp.s

.PHONY : fs/kvfs.s

# target to generate assembly for a file
fs/kvfs.cpp.s:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs/kvfs.cpp.s
.PHONY : fs/kvfs.cpp.s

fs_main.o: fs_main.cpp.o

.PHONY : fs_main.o

# target to build an object file
fs_main.cpp.o:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs_main.cpp.o
.PHONY : fs_main.cpp.o

fs_main.i: fs_main.cpp.i

.PHONY : fs_main.i

# target to preprocess a source file
fs_main.cpp.i:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs_main.cpp.i
.PHONY : fs_main.cpp.i

fs_main.s: fs_main.cpp.s

.PHONY : fs_main.s

# target to generate assembly for a file
fs_main.cpp.s:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/fs_main.cpp.s
.PHONY : fs_main.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

util/hash_function.o: util/hash_function.cpp.o

.PHONY : util/hash_function.o

# target to build an object file
util/hash_function.cpp.o:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/util/hash_function.cpp.o
.PHONY : util/hash_function.cpp.o

util/hash_function.i: util/hash_function.cpp.i

.PHONY : util/hash_function.i

# target to preprocess a source file
util/hash_function.cpp.i:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/util/hash_function.cpp.i
.PHONY : util/hash_function.cpp.i

util/hash_function.s: util/hash_function.cpp.s

.PHONY : util/hash_function.s

# target to generate assembly for a file
util/hash_function.cpp.s:
	$(MAKE) -f CMakeFiles/fs_main.dir/build.make CMakeFiles/fs_main.dir/util/hash_function.cpp.s
.PHONY : util/hash_function.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fs_main"
	@echo "... test"
	@echo "... fs/adaptor.o"
	@echo "... fs/adaptor.i"
	@echo "... fs/adaptor.s"
	@echo "... fs/config.o"
	@echo "... fs/config.i"
	@echo "... fs/config.s"
	@echo "... fs/inode.o"
	@echo "... fs/inode.i"
	@echo "... fs/inode.s"
	@echo "... fs/kvfs.o"
	@echo "... fs/kvfs.i"
	@echo "... fs/kvfs.s"
	@echo "... fs_main.o"
	@echo "... fs_main.i"
	@echo "... fs_main.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... util/hash_function.o"
	@echo "... util/hash_function.i"
	@echo "... util/hash_function.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

